# SPDX-FileCopyrightText: 2022-present Intel Corporation
# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

# Disable 4G Control Plane
omec-control-plane:
  enable4G: false

# Disable 5G RAN Simulator
5g-ran-sim:
  enable: false

# Override values for 5g-control-plane Helm Chart
# https://gerrit.opencord.org/sdcore-helm-charts/5g-control-plane/values.yaml
5g-control-plane:
  enable5G: true
  images:
    repository: ""    # defaults to Docker Hub
    #tags:
    #  amf: <amf image tag>
    # refer to above Helm Chart to add other NF images

  kafka:
    deploy: true

  mongodb:
    usePassword: false
    persistence:
      enabled: false
    architecture: replicaset
    replicaCount: 2
  resources:
    enabled: false

  config:
    mongodb:
      name: free5gc
      url: mongodb://mongodb-arbiter-headless #enable if cluster deployment required
      authKeysDbName: authentication
      authUrl: mongodb://mongodb-arbiter-headless

    managedByConfigPod:
      enabled: true
      syncUrl: http://sdcore-adapter-v2-1.aether-roc.svc:8080/synchronize

    sctplb:
      deploy: false # if enabled then deploy sctp pod.
                    # Once backend is stable, this option will be enabled by default

    upfadapter:
      deploy: false # If enabled then deploy upf adapter pod.
                    # Once backend is stable, this option will be enabled by default

    metricfunc:
      deploy: true

    # Change AMF config here if rquired Most of the AMF config comes from Slice APIs
    # but some of the config is directly provided  thorugh helm chart
    amf:
      # Use externalIP if you need to access AMF from remote setup
      # and you don't want setup NodePort Service Type
      ngapp:
        externalIp: {{ ansible_default_ipv4.address }}
        port: 38412
      cfgFiles:
        amfcfg.conf:
          configuration:
            # storing AMF subscribers in the datastore is disabled by default.
            # Once internal testing is complete we will enable DBStore by default.
            enableDBStore: false

    # SMF config override. Refer helm chart values for more options.
    smf:
      cfgFiles:
        smfcfg.conf:
          configuration:
            # Storing AMF subscribers in the datastore is disabled by default.
            # Once internal testing is complete we will enable DBStore by default.
            enableDBStore: false

    #pcf:
    #  cfgFiles:
    #    pcfcfg.conf:
    #      configuration:

    nrf:
      cfgFiles:
        nrfcfg.conf:
          configuration:
            mongoDBStreamEnable: false    # enable/disable MongoDB stream in NRF.
            nfProfileExpiryEnable: false  # if enabled, remove NF profile if no keepalive received
            nfKeepAliveTime: 60           # default timeout for NF profiles


# Override values for omec-sub-provision (subscriber) Helm Chart
# https://gerrit.opencord.org/sdcore-helm-charts/omec-sub-provision/values.yaml
# ***Note: Most of these values can (and should) be set via ROC API***
omec-sub-provision:
  enable: true
  images:
    repository: ""    # defaults to Docker Hub
    #tags:
    #  simapp: #add simapp override image

  config:
    simapp:
      cfgFiles:
        simapp.yaml:
          configuration:
            provision-network-slice: {{ core.standalone }} # if enabled, Device Groups & Slices configure by simapp
            sub-provision-endpt:
              addr: webui.omec.svc.cluster.local  # subscriber configuation endpoint.
            # sub-proxy-endpt: # used if subscriber proxy is enabled in the ROC.
            #   addr: subscriber-proxy.aether-roc.svc.cluster.local
            #   port: 5000

            # Configure Subscriber IMSIs and their security details.
            # You can have any number of subscriber ranges
            # This block is always necessary to establish range(s) of valid IMSIs
            subscribers:
            - ueId-start: "208930100007487"
              ueId-end: "208930100007500"
              plmnId: "20893"
              opc: "981d464c7c52eb6e5036234984ad0bcf"
              op: ""
              key: "5122250214c33e723a5dd523fc145fc0"
              sequenceNumber: "16f3b3f70fc2"
            - ueId-start: "208930100007501"
              ueId-end: "208930100007586"
              plmnId: "20893"
              opc: "981d464c7c52eb6e5036234984ad0bcf"
              op: ""
              key: "5122250214c33e723a5dd523fc145fc0"
              sequenceNumber: "16f3b3f70fc2"

            # Configure Device Groups (ignored if provision-network-slice is disabled)
            device-groups:
            - name:  "5g-gnbsim-user-group1"
              imsis:
                - "208930100007487"
                - "208930100007488"
                - "208930100007489"
                - "208930100007490"
                - "208930100007491"
                - "208930100007492"
                - "208930100007493"
                - "208930100007494"
                - "208930100007495"
                - "208930100007496"
                - "208930100007497"
                - "208930100007498"
                - "208930100007499"
                - "208930100007500"
                - "208930100007501"
                - "208930100007502"
                - "208930100007503"
                - "208930100007504"
                - "208930100007505"
                - "208930100007506"
                - "208930100007507"
                - "208930100007508"
                - "208930100007509"
                - "208930100007510"
                - "208930100007511"
                - "208930100007512"
                - "208930100007513"
                - "208930100007514"
                - "208930100007515"
                - "208930100007516"
                - "208930100007517"
                - "208930100007518"
                - "208930100007519"
                - "208930100007520"
                - "208930100007521"
                - "208930100007522"
                - "208930100007523"
                - "208930100007524"
                - "208930100007525"
                - "208930100007526"
                - "208930100007527"
                - "208930100007528"
                - "208930100007529"
                - "208930100007530"
                - "208930100007531"
                - "208930100007532"
                - "208930100007533"
                - "208930100007534"
                - "208930100007535"
                - "208930100007536"
                - "208930100007537"
                - "208930100007538"
                - "208930100007539"
                - "208930100007540"
                - "208930100007541"
                - "208930100007542"
                - "208930100007543"
                - "208930100007544"
                - "208930100007545"
                - "208930100007546"
                - "208930100007547"
                - "208930100007548"
                - "208930100007549"
                - "208930100007550"
                - "208930100007551"
                - "208930100007552"
                - "208930100007553"
                - "208930100007554"
                - "208930100007555"
                - "208930100007556"
                - "208930100007557"
                - "208930100007558"
                - "208930100007559"
                - "208930100007560"
                - "208930100007561"
                - "208930100007562"
                - "208930100007563"
                - "208930100007564"
                - "208930100007565"
                - "208930100007566"
                - "208930100007567"
                - "208930100007568"
                - "208930100007569"
                - "208930100007570"
                - "208930100007571"
                - "208930100007572"
                - "208930100007573"
                - "208930100007574"
                - "208930100007575"
                - "208930100007576"
                - "208930100007577"
                - "208930100007578"
                - "208930100007579"
                - "208930100007580"
                - "208930100007581"
                - "208930100007582"
                - "208930100007583"
                - "208930100007584"
                - "208930100007585"
                - "208930100007586"
              ip-domain-name: "pool1"
              ip-domain-expanded:
                dnn: internet
                dns-primary: "8.8.8.8"        # Value is sent to UE
                mtu: 1460                     # Value is sent to UE when PDU Session Established
                ue-ip-pool: "172.250.1.0/16"  # IP address pool for subscribers
                ue-dnn-qos:
                  dnn-mbr-downlink: 500       # UE level downlink QoS (Maximum bit rate per UE)
                  dnn-mbr-uplink:   500       # UE level uplink QoS (Maximum bit rate per UE)
                  bitrate-unit: Mbps          # Unit for above QoS rates
                  traffic-class:              # Default bearer QCI/ARP (not used in 5G)
                    name: "platinum"
                    qci: 9
                    arp: 6
                    pdb: 300
                    pelr: 6
              site-info: "enterprise"
            # UPF allocates IP address if there is only 1 device-group
            # SMF allocates IP address if there is >1 device-group

            # Configure Network Slices (ignored if provision-network-slice is disabled)
            network-slices:
            - name: "default"      # can be any unique slice name
              slice-id:            # must match with slice configured in gNB, UE
                sd: "010203"
                sst: 1
              site-device-group:
              - "5g-gnbsim-user-group1"   # All UEs in this device-group are assigned to this slice
              # Applicaiton filters control what each user can access.
              # Default, allow access to all applications
              application-filtering-rules:
              - rule-name: "ALLOW-ALL"
                priority: 250
                action: "permit"
                endpoint: "0.0.0.0/0"
              site-info:
                # Provide gNBs and UPF details and also PLMN for the site
                gNodeBs:
                - name: "gnb1"
                  tac: 1
                - name: "gnb2"
                  tac: 2
                plmn:
                  mcc: "208"
                  mnc: "93"
                site-name: "enterprise"
                upf:
                  upf-name: "upf"  # associated UPF for this slice. One UPF per Slice.
                  upf-port: 8805

# Override values for omec-user-plane Helm Chart
# https://gerrit.opencord.org/sdfabric-helm-charts/bess-upf/values.yaml
omec-user-plane:
  enable: true
  nodeSelectors:
    enabled: true
  resources:
    enabled: false
  images:
    repository: ""    # defaults to Docker Hub
    # following two lines pull busybox from Docker Hub instead of Aether Registry
    tags:
      tools: omecproject/busybox:stable
    # uncomment following section to add update bess image tag
    #tags:
    #  bess: <bess image tag>
    #  pfcpiface: <pfcp image tag>
  config:
    upf:
      name: "oaisim"
      sriov:
        enabled: false    # SRIOV is disabled by default
      hugepage:
        enabled: false    # Should be enabled if DPDK is enabled
      cniPlugin: macvlan  # Can be any other plugin. Dictates how IP address are assigned
      ipam: static
      routes:
        - to: {{ ansible_default_ipv4.address }}
          via: 169.254.1.1
      enb:
        subnet: {{ ran_subnet }} # Subnet for the gNB network
      access:
        iface: {{ core.data_iface }}
        gateway: 192.168.252.1
        ip: 192.168.252.3/24
      core:
        iface: {{ core.data_iface }}
        gateway: 192.168.250.1
        ip: 192.168.250.3/24
      cfgFiles:
        upf.jsonc:
          mode: af_packet                # This mode implies no DPDK
          hwcksum: true
          log_level: "trace"
          measure_upf: true
          measure_flow: true
          gtppsc: true                   # Extension header enabled in 5G.
          cpiface:
            dnn: "internet"              # Must match Slice dnn
            hostname: "upf"
            #http_port: "8080"
            enable_ue_ip_alloc: false    # If true, UPF allocates address from following pool
            ue_ip_pool: "172.250.0.0/16" # IP pool used UEs if enable_ue_ip_alloc=true
          slice_rate_limit_config:       # Slice-level rate limiting (also controlled by ROC)
            # Uplink
            n6_bps: 10000000000          # 10Gbps
            n6_burst_bytes: 12500000     # 10ms * 10Gbps
            # Downlink
            n3_bps: 10000000000          # 10Gbps
            n3_burst_bytes: 12500000     # 10ms * 10Gbps
